### ISSUE TITLE
SocketTimeoutException when resolving SRV record of isode.com

### ISSUE THREAD

**Issue by iNPUTmice** [rtreffer/minidns#18]
Hi,

MiniDNS throws a timeout exception when resolving the _xmpp-client._tcp  SRV record of isode.com. 

see https://github.com/siacs/Conversations/issues/1130

**Comment by Flowdalic** [comment]
Could you show us the stacktrace of the exception?

**Comment by Flowdalic** [comment]
Does work for me on Linux:

```
res2: de.measite.minidns.DNSMessage = 
-- DNSMessage 24629 --
Q[Question/IN/SRV: _xmpp-client._tcp.isode.com]NS[]A[RR SRV/IN: SRV xmpp.isode.com:5221 p:5 w:1, RR SRV/IN: SRV xmpp.isode.com:5220 p:5 w:1, RR SRV/IN: SRV xmpp.isode.com:5222 p:5 w:1]ARR[]
```

(which reminds me to prettify `toString()` in MiniDNS)

**Comment by Flowdalic** [comment]
BTW is this reproducible? Otherwise, can't it simply be that the remote host is not reachable at the time of lookup and thus the `SocketTimeoutException` is thrown?

**Comment by iNPUTmice** [comment]
argh sorry for the noise. It was in fact a combination of a bug in my wrapper code and one of my DNS servers not responding. I just looked at the wrong error message. Trying to get you the stack trace brought me back on the right track.
