### ISSUE TITLE
0.2.0 release

### ISSUE THREAD

**Issue by arnt** [rtreffer/minidns#30]
Hi,

DNSSEC has been merged, so what's blocking a 0.2.0 release?

**Comment by Flowdalic** [comment]
I've pushed the last changes I wanted to see integrated just yesterday. Rene will prepare and publish a beta release the next week.

**Comment by arnt** [comment]
Lovely. Thanks.

**Comment by Flowdalic** [comment]
0.2.0-alpha2 has been published on Maven Central: http://search.maven.org/#search%7Cgav%7C1%7Cg%3A%22de.measite.minidns%22%20AND%20a%3A%22minidns-dnssec%22

As you may have noticed: This is an alpha release, and MiniDNS hasn't had a paid review for security issues. Feedback, bugs, issues, ideally with fixes and test cases are welcome. :)
