### ISSUE TITLE
can not resolve library from gradle

### ISSUE THREAD

**Issue by siavashabdoli** [rtreffer/minidns#42]
I import smack to my project but minidns module can not resolve. this error occurs:
`Could not resolve de.measite.minidns:minidns:[0.1,0.2)`
it tries to import 0.1.7 version

also I try to exclude it from smack and import it separately with this line:
`compile 'de.measite.minidns:minidns-core:0.2.0-beta1'`

and i get this error:
Error:(176, 13) Failed to resolve: de.measite.minidns:minidns-core:0.2.0-beta1

**Comment by Flowdalic** [comment]
This is more a generic question about how gradle does resolves artifacts. I don't think it belongs in the MiniDNS issue tracker, but still: Which Maven repositories have you configured? MiniDNS 0.2.0-beta1 is available on Maven Central.

**Comment by siavashabdoli** [comment]
no I set maven central already and every library works fine except MiniDns. also I have sample project that works 1 month ago and there is no changes on it in this month I check that project too and without any changes MiniDns can not resolve. definitely there is problem with MiniDns. maybe other people use cached repository, so they resolve it from their cache.

P.S: I can not wait for fix so I fix it with jar library.

**Comment by siavashabdoli** [comment]
I restart android studio and problem not happened again! seriously android studio is a weird IDE!
