### ISSUE TITLE
PTR lookup from IP need full name

### ISSUE THREAD

**Issue by ppanero** [rtreffer/minidns#58]
I could not find in the documentation (is there more appart from the README.md file?) how to make a PTR query work. 

The following is not working, giving back a NX_DOMAIN:
```java
ResolverApi.INSTANCE.resolve("172.217.0.174", classOf[PTR])
```
The following works but I had to manually construct the name to query. Is there a way to get that? if not, is an implementation for it in the roadmap?
```java
ResolverApi.INSTANCE.resolve("174.0.217.172.in-addr.arpa", classOf[PTR])
```

**Comment by Flowdalic** [comment]
Good point. I think it may be sensible to add

```java
ResolverResult<PTR> ResolverApi.reverseLookup(InetAddress);
```

as part of ResolverApi.
