### ISSUE TITLE
Access TTL of a result

### ISSUE THREAD

**Issue by ppanero** [rtreffer/minidns#59]
There is no way of accessing TTL. Only the question, response code and data (ip), auth, reasons and exceptions are available.

Is there documentation apart from the main quickstart?

**Comment by Flowdalic** [comment]
There is `DNSMessage ResolverResult.getRawAnswer()` over which the TTL of a RR can be retrieved.

**Comment by ppanero** [comment]
@Flowdalic  Is that in the MVN / SBT repositories? The compilide version (0.2.1) im getting does not contain that method but I do see it in the code

**Comment by Flowdalic** [comment]
> @Flowdalic Is that in the MVN / SBT repositories?

Unfortunately no, not yet.
