### ISSUE TITLE
Build issues when including in projects via subtree merge

### ISSUE THREAD

**Issue by SamWhited** [rtreffer/minidns#9]
While making your build process dependant on version control seems like a good idea (eg. see [here](https://github.com/rtreffer/minidns/blob/master/build.gradle#L21)) it actually causes problems when using version control in other projects. If, for instance, your project is included in another project via Git's subtree merge strategy (or in another project that doesn't use Git at all), the build breaks.

Please consider removing your build dependency on Git.

**Comment by rtreffer** [comment]
Hi,

The reason I am going after git is simple: I never ever want to push a version that can not be reproduced from the sources. It should be idiot safe (with the idiot being me in that case).

I've just pushed an inversion of that logic: I simply use dev-SNAPSHOT and only go after git _if_ it is s.th. different.

That should fix build issues if you use it somewhere else. Please reopen if it does not fix the issue.
